name: test workflow
run-name: test
on:
  workflow_dispatch:
jobs:
  test-job:
    runs-on: windows-latest
    steps:
      - name: set build steps
        id: get_build_steps
        shell: bash
        run: |
          case ${{inputs.target-platform-short-name}} in
            "Windows")
              echo package_command="package-windows" >> "$GITHUB_OUTPUT"
              echo create_command="create-win-exe" >> "$GITHUB_OUTPUT"
            ;;
            "Mac")
              echo package_command="package-mac" >> "$GITHUB_OUTPUT"
              echo create_command="create-mac-exe" >> "$GITHUB_OUTPUT"
            ;;
            "Linux")
              echo package_command="package-linux" >> "$GITHUB_OUTPUT"
              echo create_command="create-lin-exe" >> "$GITHUB_OUTPUT"
            ;;
            *)
              echo "Incorrect os input"
              exit 1
            ;;
          esac

      # Create Application Package
      - name: Create ${{inputs.target-platform-short-name}} Package
        run: npm run ${{steps.get_build_steps.outputs.package_command}}

      # Create Application Installer
      - name: Create ${{inputs.target-platform-short-name}} Installer
        run: npm run ${{steps.get_build_steps.outputs.create_command}}
    
